<?php

/* ==================================================
	 MARK THOMAS FILMS
	 ASSET LOADER
	 ================================================== */

/* This file itself should always be revalidated so changes to the JS manifest are picked up promptly.
 * Individual CSS/JS assets use file modification timestamps for cache busting.
 */

header('Content-Type: application/javascript; charset=UTF-8');
header('Cache-Control: no-cache, must-revalidate');

/* ==================================================
	 CONFIGURATION
	 ================================================== */

$baseUrl =
		'/kurtiskronk/markthomasfilms';

/* JAVASCRIPT MANIFEST
 * Only files explicitly listed here will execute.
 * Order matters. If one file depends on another, put the dependency first.
 */

$jsManifest = array(
		'films.js',
		'form.js',
		'site.js'

		/*
		 * Add future files here:
		 *
		 * 'reviews.js',
		 * 'site-ui.js'
		 */
);


/* ==================================================
	 FIND ALL CSS FILES
	 ================================================== */

$cssPaths =
		glob(
				__DIR__ . '/css/*.css'
		);


if ($cssPaths === false) {
		$cssPaths = array();
}


/*
 * Use natural alphabetical order.
 *
 * We don't need numbered filenames. Just keep
 * overlapping CSS rules organized logically.
 */

usort(
		$cssPaths,
		function ($a, $b) {

				return strnatcasecmp(
						basename($a),
						basename($b)
				);

		}
);


/* ==================================================
	 BUILD CSS URLS
	 ================================================== */

$cssFiles =
		array();


foreach ($cssPaths as $path) {

		if (!is_file($path)) {
				continue;
		}


		$cssFiles[] =
				$baseUrl .
				'/css/' .
				rawurlencode(
						basename($path)
				) .
				'?v=' .
				filemtime($path);

}


/* ==================================================
	 BUILD EXPLICIT JS URLS
	 ================================================== */

$jsFiles =
		array();

$missingJsFiles =
		array();


foreach ($jsManifest as $filename) {

		$filename =
				basename($filename);


		$path =
				__DIR__ .
				'/js/' .
				$filename;


		if (!is_file($path)) {

				$missingJsFiles[] =
						$filename;

				continue;

		}


		$jsFiles[] =
				$baseUrl .
				'/js/' .
				rawurlencode($filename) .
				'?v=' .
				filemtime($path);

}

?>


(function () {

	'use strict';


	/* ==================================================
		 ASSETS GENERATED BY PHP
		 ================================================== */

	const cssFiles =
		<?php
			echo json_encode(
					$cssFiles,
					JSON_UNESCAPED_SLASHES
			);
		?>;


	const jsFiles =
		<?php
			echo json_encode(
					$jsFiles,
					JSON_UNESCAPED_SLASHES
			);
		?>;


	const missingJsFiles =
		<?php
			echo json_encode(
					$missingJsFiles,
					JSON_UNESCAPED_SLASHES
			);
		?>;


	/* ==================================================
		 REPORT MISSING MANIFEST FILES
		 ================================================== */

	missingJsFiles.forEach(
		function (filename) {

			console.warn(
				'Mark Thomas Films: JS file listed in loader but not found:',
				filename
			);

		}
	);


	/* ==================================================
		 LOAD ALL CSS FILES
		 ================================================== */

	cssFiles.forEach(
		function (url) {

			const link =
				document.createElement('link');


			link.rel =
				'stylesheet';


			link.href =
				url;


			document.head.appendChild(
				link
			);

		}
	);


	/* ==================================================
		 LOAD JAVASCRIPT SEQUENTIALLY
		 ================================================== */

	function loadScript(index) {

		if (index >= jsFiles.length) {
			return;
		}


		const script =
			document.createElement('script');


		script.src =
			jsFiles[index];


		/*
		 * We deliberately load one JS file at a time.
		 * This keeps manifest order deterministic.
		 */

		script.onload =
			function () {

				loadScript(
					index + 1
				);

			};


		script.onerror =
			function () {

				console.error(
					'Mark Thomas Films: failed to load JS:',
					jsFiles[index]
				);


				/*
				 * Don't let one failed file prevent
				 * subsequent files from loading.
				 */

				loadScript(
					index + 1
				);

			};


		document.head.appendChild(
			script
		);

	}


	loadScript(0);

})();